### ISSUE TITLE
Unable to install via Foundry

### ISSUE THREAD

**Issue by Stonedtroll** [TheDeckOfManyStrings/anewfoe#2]
Unable to install via Foundry:

![image](https://github.com/user-attachments/assets/6a97cd70-55dd-48f9-aa87-4ea53895573b)

Foundry 12.331

**Comment by TheDeckOfManyStrings** [comment]
Hello! Thank you for submitting this issue! There were some issues with the onboarding process for this module that I have been working through with the staff. I have pushed a new minor release (v1.0.1) that has just been published to the community marketplace. I verified the install is now taking place and the module should now be functioning. I greatly appreciate you taking the time to submit an issue. Happy gaming!!!

ref: https://github.com/TheDeckOfManyStrings/anewfoe/releases/tag/1.0.1

**Comment by Stonedtroll** [comment]
Confirmed fixed. FYI: DEBUG mode is left on so it is spamming the console.
